version: '3.4'

   services:
     frontend:
       build: ./frontend
       ports:
         - "3000:3000"
       environment:
         - NODE_ENV=development

     backend:
       build: ./backend
       ports:
         - "5000:80"
       environment:
         - ASPNETCORE_ENVIRONMENT=Development